Feature/asv 825 add top up and buy flow
Aptoide/appcoins-wallet-android pull request #11
Opened 2018-07-25 09:34 UTC by paquiquinho

**DESCRIPTION:**
This PR aims to refactor the existing iab flow code so we are able to use 2 different flows; The express checkout buy flow is not working yet but all the conditions to launch it are being verified, as well as the required UI. The new dialog is being correctly populated already except for the fiat conversion. The service already exists but the endpoint is not up so I'm "mocking" the response to it. This feature can be toggled by changing the if condition on IabActivity(line 81) from true (feature **off**) to canBuy (feature **on**).

**TESTING:**
To test this feature, first turn it on in the code. Then create 2 wallets and change to the Ropsten network. Get funds on one of the wallets through the airdrop. Afterwards send buy intents to the wallet with either of the wallets selected (you can use toolbox to easily achieve this). If the wallet with funds is selected, you should see the normal buy flow and it should work as expected; If the wallet with no funds is selected you'll see the new dialog. The buy button only shows a snack;

2018-07-25 16:19 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/di/ToolsModule.java
> +    //    .client(client)
Do we need this commented code?

2018-07-31 14:09 UTC, Trinkes requested changes

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/di/ToolsModule.java
> +  private static final String TOKEN_TO_FIAT_END_POINT = "https://34.254.1.70";
did you consider to have this constant at TokenToFiatService?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/di/ToolsModule.java
> +    //return request -> {
remove commented code

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/repository/ExpressCheckoutBuyService.java
> +  public Observable<FiatValue> getTokenValue(double value) {
Why do you use Observable instead of Single?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +  @Override public void onDestroy() {
there is no reason to override this method

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +  @Override public void onDestroyView() {
release your references to the view here

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +    presenter = new ExpressCheckoutBuyPresenter(this, inAppPurchaseInteractor,
why is presenter instantiated here?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +    String valueTextCompose = valueText + " = ";
Is it possible to use a StringBuilder instead of + operator?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +  @Override public void showError() {
No error view?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +  public String getAppPackage() {
We have some duplicated code here, is it possible to merge it?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +        v -> Snackbar.make(this.getView(), "Buy triggered", BaseTransientBottomBar.LENGTH_LONG)
is this finish?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +    Single.defer(() -> Single.just(getAppPackage()))
We have some duplicated code here, is it possible to merge it?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyPresenter.java
> +  public void setupUi(String uriString) {
Why is this method public?

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyPresenter.java
> +  public void present(String uriString, String appPackage, String productName) {
appPackage and productName not used

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/RegularBuyFragment.java
> +    Single.defer(() -> Single.just(getAppPackage()))
duplicated logic

2018-07-31 14:09 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/RegularBuyFragment.java
> +public class RegularBuyFragment extends DaggerFragment implements RegularBuyView {
the name of this fragment doesn't help that much identifying the type of payment it does

2018-08-01 10:03 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/di/ToolsModule.java
> +  private static final String TOKEN_TO_FIAT_END_POINT = "https://34.254.1.70";
Fixed

2018-08-01 10:04 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/di/ToolsModule.java
> +    //return request -> {
Fixed

2018-08-01 10:04 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/repository/ExpressCheckoutBuyService.java
> +  public Observable<FiatValue> getTokenValue(double value) {
Fixed

2018-08-01 10:04 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +  @Override public void onDestroy() {
Fixed

2018-08-01 10:12 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +  @Override public void onDestroyView() {
Fixed

2018-08-01 10:15 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyFragment.java
> +    presenter = new ExpressCheckoutBuyPresenter(this, inAppPurchaseInteractor,
Fixed

2018-08-01 10:15 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyPresenter.java
> +  public void setupUi(String uriString) {
Fixed

2018-08-01 10:17 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/ui/iab/ExpressCheckoutBuyPresenter.java
> +  public void present(String uriString, String appPackage, String productName) {
Fixed

2018-08-01 10:19 UTC, paquiquinho commented on app/src/main/java/com/asfoundation/wallet/ui/iab/RegularBuyFragment.java
> +    Single.defer(() -> Single.just(getAppPackage()))
Fixed

2018-08-01 10:21 UTC, franciscoCalado commented on app/src/main/java/com/asfoundation/wallet/ui/iab/RegularBuyFragment.java
> +public class RegularBuyFragment extends DaggerFragment implements RegularBuyView {
Fixed

2018-08-21 20:58 UTC, merged