Feature/appc 699 choose payment
Aptoide/appcoins-wallet-android pull request #138
Opened 2018-12-06 00:52 UTC by FredericoSantinho

2018-12-06 16:55 UTC, Trinkes requested changes

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/Adyen.java
> +        .flatMap(status -> getPaymentMethod(status.getServices(), paymentType))
this method was only used here, consider deleting it

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentStatus.java
>    public static final AdyenPaymentStatus NULL_PAYMENT_STATUS =
not used anymore

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/repository/InAppPurchaseService.java
> +  private final TransactionIdHelper transactionIdHelper;
not used

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
> +  private void removeUnavailable(List<PaymentMethod> paymentMethods,
is adyen always available?

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +  private View appcView;
not used

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +  private View appcCreditsView;
not used

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +  private static final String DEFAULT_CURRENCY = "EUR";
not used

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +    compositeDisposable.dispose();
consider using clear instead of dispose

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +    cancelButton = null;
all views should be set to null

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +        .subscribe(__ -> {
this logic should bem on presenter side

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +    showAvailable(paymentMethods);
this logic should be on presenter

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +    compositeDisposable.add(walletService.getWalletAddress()
this should be on presenter

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.java
> +    return Currency.getInstance(currencyCode)
this should be on presenter

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.java
> +    if (savedInstanceState == null) {
be careful with the lifecycle. In this case disposables are subscribed on fist time the view is created and disposed when view is destroyed. Here If we recreate the view, click listeners are not registered

2018-12-06 16:55 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/WebViewActivity.java
> +      billingWebViewFragment.setRetainInstance(true);
put this property inside the fragment class

2018-12-06 16:55 UTC, Trinkes commented on app/src/test/java/com/asfoundation/wallet/repository/BdsPendingTransactionServiceTest.java
>      bdsPendingTransactionService = new BdsTransactionService(scheduler,
this has an error

2018-12-07 00:37 UTC, FredericoSantinho commented on app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
> +  private void removeUnavailable(List<PaymentMethod> paymentMethods,
yes

2018-12-07 16:44 UTC, merged