APPC 533 handle payment process
Aptoide/appcoins-wallet-android pull request #17
Opened 2018-08-08 07:41 UTC by JoaoRaimundo

- Get purchase details from backend
- Send purchase details back to the requesting app
- Update billing permissions
- Added workaround for single purchase request

2018-08-08 14:01 UTC, Trinkes requested changes

2018-08-08 14:01 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
> +            return null;
This will make the chain crash

2018-08-08 14:01 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
> +import android.os.Bundle;
Bundle should not be used at this layer. This InAppPurchaseInteractor.java should not be bind to android in any way.
This will make the junit tests not possible

2018-08-08 14:01 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/bds/OnChainBdsPaymentLogs.kt
> +class OnChainBdsPaymentLogs {
class not used

2018-08-08 14:01 UTC, Trinkes commented on billing/src/main/java/com/appcoins/wallet/billing/BdsBilling.kt
> +        // TODO  replace with: repository.getSkuPurchase(merchantName, sku, address, signedContent)
do it

2018-08-08 14:01 UTC, Trinkes commented on billing/src/main/java/com/appcoins/wallet/billing/BdsBilling.kt
> +            Gson().toJson(Consumed())).map { it }
remote repository should be the one serialising the data

2018-08-08 17:46 UTC, merged

2018-08-15 11:15 UTC, Hercules69 commented
Not sure what to do I'm on my own I'm still in training? Well training myself on programming Could use some help fixing my mess? Thanks