APPC-904 Top Up feature
Aptoide/appcoins-wallet-android pull request #239
Opened 2019-03-14 08:40 UTC by JoaoRaimundo

1. Added Top Up feature
2. Added main screen new button

2019-03-15 16:37 UTC, Trinkes requested changes

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
> +  private val disposables: CompositeDisposable = CompositeDisposable()
you have to dispose this disposables or you'll have leaks

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/service/LocalCurrencyConversionService.java
> +  public Single<FiatValue> getLocalCurrency() {
does make sense to chage this method name to something like "getAppcToLocalCurrencyRate"?

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
> +    val LOCAL_CURRENCY = "LOCAL_CURRENCY"
consider passing this value to the presenter instead of making the presenter access this variable

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
> +  private lateinit var transactionData: String
not used

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
> +    if (requestCode == WEB_VIEW_REQUEST_CODE) {
this is presentation logic

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
> +  override fun navigateToUri(url: String?, domain: String, skuId: String, amount: BigDecimal,
does url can be null?

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.java
> +          //Intent intent = new Intent(getContext(), TopUpActivity.class);
commented code

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.java
> +          Intent intent = navigator.getActivityIntent();
use new intent pattern instead

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.java
> +      currentDomain = savedInstanceState.getString(DOMAIN);
since currentDomain variable doesn't change, it's not needed so save on savedInstanceState

2019-03-15 16:37 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
> +  public Single<Double> getTransactionAmount(String uid) {
can you remove duplicated code in getTransactionAmount and getTransactionUid methods?

2019-03-21 16:42 UTC, Trinkes requested changes

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/navigator/UriNavigator.java
> +import android.app.Activity;
not used

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/navigator/UriNavigator.java
> +import com.asfoundation.wallet.entity.TransactionBuilder;
not used

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/service/LocalCurrencyConversionService.java
> +        .subscribeOn(Schedulers.io());
The scheduler should not be defined at this level

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/WebViewActivity.java
> +  private static UriNavigator navigator;
this cannot be static, it will cause a leak

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/iab/WebViewActivity.java
> +    intent.putExtra(DOMAIN, amount);
amount value used instead of domain?

2019-03-21 16:42 UTC, Trinkes commented on billing/src/main/java/com/appcoins/wallet/billing/BillingMessagesMapper.kt
> +    internal const val TOP_UP_AMOUNT = "top_up_amount"
the key to the bundle's value should have the same variable

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
> +    presenter.present()
the presenter should know when the screen is created so it can decide to show or not the fragment

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/payment/PaymentAuthFragment.kt
> +    navigator = PaymentFragmentNavigator((activity as UriNavigator?)!!, topUpView!!)
The onAttach method should be used to do this

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/payment/PaymentAuthFragment.kt
> +  val currentCurrency: String
lazy load this data

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
> +  private fun handleAmountChange() {
use the previous subscribed chain instead of subscribing a new one

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
> +  private var switchingCurrency: Boolean = false
Let presenter control this variable

2019-03-21 16:42 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
> +    view.getEditTextChanges().map {
disposable not handled

2019-03-21 16:49 UTC, Trinkes requested changes

2019-03-21 16:49 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/service/TransactionsNetworkClient.java
> +      if (!BuildConfig.DEBUG) {
we should check if it's main network or not instead

2019-03-22 10:19 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
> +  private fun handleAmountChange() {
Since the edittext is not enable when the ui is setup, I've changed the logic.

2019-03-27 16:20 UTC, Trinkes requested changes

2019-03-27 16:20 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/payment/PaymentAuthPresenter.java
> +    disposables.add(defaultWalletInteract.find()
what does this code do?

2019-03-27 16:20 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/topup/payment/PaymentAuthFragment.kt
> +    networkErrorDialog =
you have to dispose this observables

2019-03-27 20:31 UTC, Trinkes approved these changes

2019-03-27 20:32 UTC, merged