[feature/APPC-923] - Update transactions empty screen
Aptoide/appcoins-wallet-android pull request #257
Opened 2019-03-29 18:34 UTC by joaopmgouveia

2019-04-11 14:54 UTC, JoaoRaimundo commented on app/src/main/res/layout/layout_empty_transactions.xml
> +          android:id="@+id/no_transactions_text"
Please remove this button and its action. This is no longer needed.

2019-04-16 16:45 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/widget/EmptyTransactionsView.java
> +      boolean isMainNetwork, String bonus) {
isMainNetwork value not being used. Please remove it.

2019-04-16 16:48 UTC, JoaoRaimundo commented on app/src/main/res/layout/layout_empty_transactions.xml
> +          android:text="@string/gamification_home_body"
Adding default string containing replacement tag is not a good if string is not replaced.

2019-04-16 16:49 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/widget/EmptyTransactionsView.java
> +    earnBonusTextView.setText(getResources().getString(R.string.gamification_home_body, bonus));
Validation for null string is not being done, this may go wrong.

2019-04-26 14:12 UTC, Trinkes requested changes

2019-04-26 14:12 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/ui/TransactionsActivity.java
>    public static final String LEARN_MORE_INFO_URL = "https://appcoins.io/";
remove if it's not used anymore

2019-04-26 14:18 UTC, Trinkes approved these changes

2019-04-26 14:24 UTC, merged