[feature/APPC-1037] - Implement empty transactions screen carousel
Aptoide/appcoins-wallet-android pull request #323
Opened 2019-05-31 14:48 UTC by joaopmgouveia

**What does this PR do?**

   Adds a ViewPager with 2 pages, one for the old empty transactions screen and one for the new carousel. Now both the clickable text and animation are clickable: the old screen still opens the gamification screen and the carousel opens either the Aptoide Appstore app or the browser

**Database changed?**

   No

**Where should the reviewer start?**

- EmptyTransactionsView.java

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APPC-1037](https://aptoide.atlassian.net/browse/APPC-1037)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-1037](https://aptoide.atlassian.net/browse/APPC-1037)

**Questions:**

   - Infinite swipe implementation was taking too much time and thus is not included in this PR

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2019-06-14 15:47 UTC, JDSM01 requested changes
1- When you scroll to the opposite side of the other view, the animation restarts.
2- When you click on “Discover Top Apps” or its image and you cancel in the complete action dialog and then you click on the text or view again it launches 2 dialogs instead of 1. Every time you do this it adds 1 more dialog.
3- By solving number 2, this will probably be solved. the randomize should only not occur when on resume (when the dialog opens and you cancel it)

2019-06-14 15:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/widget/EmptyTransactionsView.java
> +    disposables = new CompositeDisposable();
Initialise it in the activity and pass it in the constructor

2019-06-14 15:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/widget/EmptyTransactionsView.java
> +  private final int action[] =
These array can be created locally

2019-06-14 15:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/TransactionsActivity.java
> +          new EmptyTransactionsView(this, String.valueOf(maxBonus), emptyTransactionsSubject, this);
I’m not sure, but I think that if you move the systemView.showEmpty outside of the if, it should solve the problem of launching more than 1 intent

2019-06-14 15:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/TransactionsActivity.java
> +            emptyTransactionsSubject, this);
Same as above

2019-06-14 15:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/widget/adapter/EmptyTransactionPagerAdapter.kt
> +class EmptyTransactionPagerAdapter(private val anim: IntArray,
variable name: anim -> animation

2019-06-19 15:43 UTC, carvalho2707 approved these changes

2019-06-19 15:43 UTC, merged