[feature/APPC-1117] - Successful payment bonus animation
Aptoide/appcoins-wallet-android pull request #328
Opened 2019-06-17 10:26 UTC by joaopmgouveia

**What does this PR do?**

   This PR implements the animation that's shown after completing a purchase with a payment method that is eligible for bonus.

**Database changed?**

   No

**Where should the reviewer start?**

- AdyenAuthorizationFragment.java
- OnChainBuyFragment.java
- fragment_iab_transaction_completed.xml

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APPC-1117](https://aptoide.atlassian.net/browse/APPC-1117)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-1117](https://aptoide.atlassian.net/browse/APPC-1117)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2019-06-18 14:03 UTC, JDSM01 requested changes
When you’re on the complete screen and you rotate the screen, it’s suppose to keep that screen in landscape (unless it’s being killed from the previous activity, which it looks by the logs, but we can talk about it)

2019-06-18 14:03 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/AdyenAuthorizationPresenter.java
> +                .andThen(Completable.timer(view.getAnimationDuration(), TimeUnit.MILLISECONDS))
I think it’s better to pass the duration on the present method (or in the presenter constructor) instead as we should avoid presenter methods asking for view states/attributes

2019-06-18 14:03 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyFragment.java
> +import android.util.Log;
Codestyle/Import.

2019-06-18 14:03 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyFragment.java
> +  public static final String BONUS_KEY = "bonus";
Can be private. Same for the other 2 (although they were already there)

2019-06-18 14:03 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.java
> +                .andThen(Completable.timer(view.getAnimationDuration(), TimeUnit.MILLISECONDS))
same as above

2019-06-19 11:45 UTC, JDSM01 reviewed
Ignore the general error reported before

2019-06-19 15:54 UTC, carvalho2707 approved these changes

2019-06-19 15:54 UTC, merged