Feature/appc 695 get transaction from backend
Aptoide/appcoins-wallet-android pull request #336
Opened 2019-06-19 13:17 UTC by Trinkes

**What does this PR do?**

   This PR changes the source of transactions shown at transactions screen from Trust api to our backend api

**Database changed?**

   Yes

**Where should the reviewer start?**

- [ ] FetchTransactionsInteract.java
- [ ] TransactionRepositoryType.java and its implementations

**How should this be manually tested?**

open the dev version of the wallet and import or generate transactions or payments. Those actions should appear at transactions screen.
 
**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-595](https://aptoide.atlassian.net/browse/APPC-595)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2019-06-28 10:46 UTC, JDSM01 requested changes
Unused Imports in: RepositoriesModules, TransactionsModule, ProdTransactionRepository, TransactionsViewModelFactory
Unused methods in: TransactionsNetworkClientType
Conflicts

2019-06-28 10:46 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/repository/ProdTransactionRepository.kt
> +  private fun getOffChainTransactions(wallet: String): Observable<List<Transaction>> {
Why are we trying to get offchain transactions here? This will only run if for some reason we are in Prod and are using the ropsten network

2019-06-28 10:46 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/repository/ProdTransactionRepository.kt
> +    return Observable.merge(getOnchainTransactions(networkInfo, wallet),
I think networkInfo should not be passed as an argument to this method since it’s a field of the class

2019-06-28 10:46 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/repository/TransactionTypeConverter.kt
> +  fun convertTransactionType(type: TransactionEntity.TransactionType): String {
All these methods can be private

2019-06-28 10:46 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/transactions/TransactionsMapper.java
>    public static final String ADS_METHOD_ID = "0xd5bde837";
Not from this PR, but these can be private

2019-07-02 18:27 UTC, Trinkes commented on app/src/main/java/com/asfoundation/wallet/transactions/TransactionsMapper.java
>    public static final String ADS_METHOD_ID = "0xd5bde837";
done

2019-07-03 08:59 UTC, JDSM01 approved these changes

2019-07-03 09:01 UTC, merged