[feature/APPC-1163] - Gamification details screen update
Aptoide/appcoins-wallet-android pull request #403
Opened 2019-08-07 16:23 UTC by joaopmgouveia

**What does this PR do?**

   This PR implements changes to the "How it works" gamification screen by turning it into a BottomSheet. Some modifications were also made to the main gamification screen.

"My level" screen: https://zpl.io/aX56OEj
"How it works" screen: https://zpl.io/2jMgNo4

**Database changed?**

   No

**Where should the reviewer start?**

- RewardsLevelActivity.kt
- MyLevelFragment.kt
- HowItWorksFragment.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APPC-1163](https://aptoide.atlassian.net/browse/APPC-1163)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-1163](https://aptoide.atlassian.net/browse/APPC-1163)

**Questions:**

There will be another PR which will deal with the possibility of implementing offline first when entering the gamification screen without internet connection

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2019-08-08 08:54 UTC, JDSM01 requested changes
Remove unused How It works fragment and logic
Remove how it works info button visibility logic

2019-08-08 10:47 UTC, JDSM01 requested changes
BottomSheet amounts are a little below of the required by the design

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/HowItWorksFragment.kt
> +  private lateinit var totalSpendSkeleton: LottieAnimationView
Not needed

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/HowItWorksFragment.kt
> +    val currentLevelColour = Color.parseColor("#001727")
This color has an entry on the colors.xml use it instead

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/HowItWorksFragment.kt
> +  override fun showPeekInformation(totalSpend: BigDecimal, bonusEarned: FiatValue) {
Interface has the wrong variable name

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/HowItWorksFragment.kt
> +    if (userStatus.level == 4) {
The 4 could be a static variable. I know it’s not being used anywhere else, but for future purposes.

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/HowItWorksPresenter.kt
> +              view.showLevels(it.first, it.second)
Not from this PR, but can you put this everything on the same line

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/HowItWorksPresenter.kt
> +            }
same as above

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/HowItWorksFragment.kt
> +      val messageTextView = view.findViewById<TextView>(R.id.message)
spendTextView maybe?

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/MyLevelFragment.kt
> +    backgroundFadeView = view.findViewById(R.id.background_fade_animation)
view.findViewById not needed

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/MyLevelFragment.kt
> +    val icon: ImageView = levelIcon?.findViewById(R.id.level_active_icon) as ImageView
Clean not needed casts and null possibilities

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/MyLevelFragment.kt
> +    val bonusLabel: Int = if (isCurrentLevel) {
Int not needed

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/MyLevelPresenter.kt
> +                       private val gamificationView: GamificationView?,
Change to gamificationActivity (variable name)

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/MyLevelPresenter.kt
> +        }!!.subscribe())
Change to gamificationView.let{disposables.add(it.getInfo...}

2019-08-08 10:47 UTC, JDSM01 commented on app/src/main/res/layout/fragment_gamification_how_it_works.xml
> +      android:visibility="visible"
Not needed

2019-08-08 12:53 UTC, JDSM01 requested changes

2019-08-08 12:53 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/MyLevelPresenter.kt
> +    activity.let {
My bad, you need to use ? before the let and then remove the !!

2019-08-08 12:53 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/MyLevelPresenter.kt
> +      disposables.add(it!!.getInfoButtonClick()!!.doOnNext {
And then use the !! on the return method of the fragment

2019-08-09 11:19 UTC, JDSM01 requested changes
- [ ] Sometimes when you enter the gamification screen the level graphic doesn’t show up. This happens more, but not always when in the transactions view, the transactions are still loading.

- [X] The loading from the how it works fragment is not using the theme colour

- [X] If you have network, go to the view (with a wallet level different from 1), go back, disable network, then go to the view, it shows level 1, but all the icons are highlighted and no lines between them

2019-08-12 09:42 UTC, carvalho2707 reviewed
Shouldn't we have the same style for all progress bars?

2019-08-12 09:53 UTC, carvalho2707 commented
> Shouldn't we have the same style for all progress bars?

This will be implemented in a different ticket

2019-08-12 09:53 UTC, carvalho2707 approved these changes

2019-08-12 09:53 UTC, merged