[hotfix] Added condition to Poa limit reached to avoid spam
Aptoide/appcoins-wallet-android pull request #498
Opened 2019-10-17 17:17 UTC by JDSM01

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-<Jira ticket number>)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-<Jira ticket number>)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2019-10-17 17:26 UTC, carvalho2707 requested changes

2019-10-17 17:26 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/advertise/CampaignInteract.kt
> +    if (savedTime != (-1).toLong()) {
There's no need to use "(-1).toLong()" , 0L should be enough

2019-10-17 17:26 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/repository/PreferenceRepositoryType.kt
> +  fun getPoaNotifiationSeenTime(): Long
Small typo in word Notification

2019-10-17 17:26 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/repository/PreferenceRepositoryType.kt
No need for this empty line

2019-10-17 17:26 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/advertise/Advertising.kt
> +
No need for this empty line

2019-10-17 17:26 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/advertise/AppCoinsAdvertisingBinder.kt
> +        }
I think that it's better if we extract this logic into a private method to improve readability.
Extra: why negate the if condition if we can change the method name?

2019-10-17 17:26 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/advertise/WalletPoAService.java
> +          if (!campaignInteract.hasSeenPoaNotification()) {
Extra: why negate the if condition if we can change the method name?

2019-10-18 07:44 UTC, closed without merging

2019-10-18 08:00 UTC, JDSM01 commented
This was not based on master and so another PR will be opened