[APPC-1449] Fixed wrong wallet verification status when no internet connection
Aptoide/appcoins-wallet-android pull request #515
Opened 2019-10-29 11:27 UTC by carvalho2707

**What does this PR do?**

   This PR fixed an use case where the settings screen would show a wrong wallet validation status if no network connection is available

**Database changed?**

  No

**Where should the reviewer start?**

- [ ] SettingsFragment.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APPC-1449](https://aptoide.atlassian.net/browse/APPC-1449)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-1449](https://aptoide.atlassian.net/browse/APPC-1449)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2019-10-29 12:35 UTC, JDSM01 requested changes

2019-10-29 12:35 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/interact/SmsValidationInteract.kt
> +          .apply()
This logic should be inside the sharedPreference. The only thing that should be here is the if

2019-10-29 12:35 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/interact/SmsValidationInteract.kt
> +    private const val WALLET_VERIFIED = "wallet_verified_"
This should also go to the shared preferences

2019-10-29 12:35 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/SettingsPresenter.kt
> +    private const val WALLET_VERIFIED = "wallet_verified_"
This should be in the defaulsSharedPrefs

2019-10-29 16:53 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/di/AccountsManageModule.java
> +    return new DeleteWalletInteract(accountRepository, store, preferenceRepositoryType);
Is the preference missing an 's' a typo?

2019-10-30 09:43 UTC, JDSM01 approved these changes

2019-10-30 11:02 UTC, merged