[APPC-1437] Wallet auto update
Aptoide/appcoins-wallet-android pull request #517
Opened 2019-11-04 14:57 UTC by JDSM01

**What does this PR do?**

Implements the soft and hard update flow.
Note: The correct endpoint is still yet to be done

**Database changed?**

No

**Where should the reviewer start?**

AutoUpdateInteract.kt
IabUpdateRequired.kt
UpdateRequired.kt

**How should this be manually tested?**

Mock values on the wallet to make the correct update show up. Go to AutoUpdateService and change the method return to return the desired AutoUpdateModel

**What are the relevant tickets?**

https://aptoide.atlassian.net/browse/APPC-1437

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2019-11-05 15:10 UTC, carvalho2707 requested changes
- [ ] We should consider extracting the text color to the resources.

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/advertise/AppCoinsAdvertisingBinder.kt
>    private fun handlePoaLimit(campaign: CampaignDetails, pkgInfo: PackageInfo) {
This function name doesn't make sense anymore since we are checking for more that poa limit.
Please change it

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/navigator/UpdateNavigator.kt
> +            intent.setPackage(info.activityInfo.packageName)
Didn't you miss another break here ?

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/entity/AutoUpdateResponse.kt
> +                              val minSdk: Int)
didn't you forgot to use SerializedName here?

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/interact/AutoUpdateInteract.kt
> +    return (walletVersionCode < updateVersionCode && walletCurrentMinSdk >= updatedMinSdk)
unnecessary brackets

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/interact/AutoUpdateInteract.kt
> +    private const val PLAY_APPVIEW_URL = "https://play.google.com/store/apps/details?id="
APPVIEW -> APP_VIEW

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/interact/CardNotificationsInteractor.kt
> +    const val AUTO_UPDATE_ID = 2
conts can be private

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/res/layout-land/iab_update_required_layout.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Why do we have a relativelayout inside another relative layout?

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/res/layout/iab_update_required_layout.xml
> +        />
This view is not used

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/main/res/layout/layout_transactions_activity.xml
> +          app:layout_constraintLeft_toLeftOf="parent"
replace left with start for rtl support

2019-11-05 15:10 UTC, carvalho2707 commented on app/src/test/java/com/asfoundation/wallet/interact/AutoUpdateInteractTest.kt
> +  companion object {
Can be private

2019-11-05 15:29 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/navigator/UpdateNavigator.kt
> +            intent.setPackage(info.activityInfo.packageName)
No, this is intended so that when both are installed it chooses Vanilla

2019-11-05 15:30 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/entity/AutoUpdateResponse.kt
> +                              val minSdk: Int)
No

2019-11-06 11:23 UTC, carvalho2707 approved these changes

2019-11-06 21:40 UTC, merged