[APPC-1533] Adyen v3 sdk integration
Aptoide/appcoins-wallet-android pull request #585
Opened 2020-01-09 15:50 UTC by JDSM01

**What does this PR do?**

   Updates the adyen sdk to v3.

**Database changed?**

   No

**Where should the reviewer start?**

AdyenPaymentFragment.kt
AdyenTopUpFragment.kt

**How should this be manually tested?**

Test the many different flows:
CC, saved CC, change CC, pre-select CC, rotation, paypal
Above to top up
One step

**What are the relevant tickets?**

  https://aptoide.atlassian.net/browse/APPC-1533

**Questions:**

Which environment should be used in Production?
https://docs.adyen.com/checkout/android/components

Prod is not working yet, due to the latest changes on api. 

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-01-13 12:02 UTC, carvalho2707 requested changes

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
> +  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
I think we should move all the following logic until **presenter.present(savedInstanceState)** to a new method called **setupUI** and this method would have the responsability to prepare all the layout changes to show the view.
This would make the onViewCreated more simple

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
> +        ResourcesCompat.getColor(resources, R.color.btn_end_gradient_color, null)
We're calling ** ResourcesCompat.getColor** 3 times and the return value is the same.
Shoudln't we call ony once?

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
> +    outState.putBoolean(SAVE_DETAILS_KEY, adyenSaveDetailsSwitch?.isChecked ?: false)
We can't use **apply** here to outState

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
> +        .doOnNext { view?.let { KeyboardUtils.hideKeyboard(view) } }
I think we shouldn't have logic in this kind of methods.
This shouldn't only act as a click listener.
If anything is to be performed on click it should be called by the presenter

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
> +      bundle.putBoolean(PRE_SELECTED_KEY, isPreSelected)
if you use **apply** here you can save typing 20 words

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
> +                    Schedulers.io())
merge this line with the previous one

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
> +    }
Invert the if condition to improve readability

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
> +                    it.skuId, it.callbackUrl, it.type, it.toAddress())
arguments can be reorganized to improve codestyle

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpFragment.kt
> +
I don't think we should have logic inside **onViewCreated**.
In my opinion you should extract the logic to a setupUI method

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpFragment.kt
> +        ResourcesCompat.getColor(resources, R.color.btn_end_gradient_color, null)
Same as above. We can create a variable with the result and reuse it

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpFragment.kt
> +  val appPackage: String by lazy {
field can be private

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpFragment.kt
> +      bundle.putBoolean(CHIP_AVAILABILITY, chipAvailability)
use **apply** to reduce boilerplate code

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpPresenter.kt
> +      else view.showGenericError()
invert **if** condition

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpPresenter.kt
> +        uid) //TODO change to use the values sent in the first response
TODO ? 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpPresenter.kt
> +            if (paymentType == PaymentType.CARD.name) { //TODO isStored is returning always true after making a payment even if sending not to store
TODO ? 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇

2020-01-13 12:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpView.kt
> +interface AdyenTopUpView {
We should create a standard for interfaces.
With or without line breaks between methods?

2020-01-13 12:02 UTC, carvalho2707 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsApiResponseMapper.kt
> +  fun map(): Boolean = true
No need for explicit type declaration

2020-01-13 12:02 UTC, carvalho2707 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsApiResponseMapper.kt
>    }
- [ ] The last method in this file has a unused argument. Please remove it

2020-01-13 12:02 UTC, carvalho2707 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
> +        .map { responseMapper.map() }
if it simply returns true why not do it here?

2020-01-13 12:02 UTC, carvalho2707 commented on billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepository.kt
> +            paymentData)) //TODO details should be a generic object this only works if the only redirect payment we use is paypal
TODO? 🎖 🎖 🎖 🎖 🎖 🎖 🎖

2020-01-13 12:02 UTC, carvalho2707 commented on billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepository.kt
> +        }
we can do something like:

.doOnError { it.printStackTrace()}
.onErrorReturnItem(false)

2020-01-13 12:02 UTC, carvalho2707 commented on billing/src/main/java/com/appcoins/wallet/billing/adyen/PaymentMethodsResponse.kt
> +data class PaymentMethodsResponse(val price: Price, val payment: PaymentMethodsApiResponse)
In this package every data class is a separated file. Why this should be different?

2020-01-13 12:22 UTC, carvalho2707 requested changes
- [x] If the card is stored the CVC Edit Text starts focused but the keyboard don't

2020-01-14 12:31 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
> +      bundle.putBoolean(PRE_SELECTED_KEY, isPreSelected)
I only saved 10

2020-01-14 14:22 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
> +        .map { responseMapper.map() }
Didn't want to change it but I agree

2020-01-14 14:25 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/adyen/PaymentMethodsResponse.kt
> +data class PaymentMethodsResponse(val price: Price, val payment: PaymentMethodsApiResponse)
Because it's part of that response

2020-01-15 12:30 UTC, carvalho2707 approved these changes

2020-01-15 14:28 UTC, merged