Feature/mob 395 mock integratiob with microservices subscriptions api
Aptoide/appcoins-wallet-android pull request #693
Opened 2020-04-06 10:04 UTC by carvalho2707

**What does this PR do?**

   This PR integrates the microservices API in the code

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [MOB-395](https://aptoide.atlassian.net/browse/MOB-395)

**What are the relevant tickets?**

  Tickets related to this pull-request: [MOB-395](https://aptoide.atlassian.net/browse/MOB-395)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-04-08 11:42 UTC, JDSM01 requested changes
This shouldn't have been merged with dev, but instead de feature-branch should have been. Please merge dev in feature-branch, to reduce the number of changed files

2020-04-08 14:05 UTC, JDSM01 requested changes
Why does the BillingSupportedType don't have Donation and Inapp_unmanaged?

2020-04-08 14:05 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyPresenter.java
> -            .equalsIgnoreCase(TransactionData.TransactionType.INAPP.name())) {
I would say that the INAPP verification is not needed anymore, but we do have 2 more transaction types beside INAPP and SUBS (donation and inapp_unmanaged), maybe we should keep the verification and add SUBS just for safety, or maybe check with whoever did the code (I think it was Trinkes)

2020-04-08 14:05 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/AsfInAppPurchaseInteractor.java
> +      });
Can you turn this into a private method to be more readable

2020-04-08 14:05 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/LocalPaymentInteractor.kt
>      return if (isInApp(type) && sku != null) {
Add subs to the isInApp method and change the name of the method. Or will we not support subs with local payments.

2020-04-08 14:05 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
> +        type?.let { BillingSupportedType.valueOfInsensitive(it) } ?: BillingSupportedType.INAPP
Pass this to handleOnGoingPurchase

2020-04-08 14:05 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
> +        type?.let { BillingSupportedType.valueOfInsensitive(it) } ?: BillingSupportedType.INAPP
Pass this to handleOnGoingPurchase

2020-04-08 14:05 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/util/EIPTransactionParser.java
> +    transactionBuilder.setType("inapp");//TODO pre subscriptions
TODO, did you forgot or is it for the future?

2020-04-08 14:05 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/util/OneStepTransactionParser.kt
> +    return uri.parameters[Parameters.TYPE] ?: "INAPP"
I think the default here should be INAPP_UNMANAGED

2020-04-08 14:05 UTC, JDSM01 commented on app/src/main/res/xml/network_security_config.xml
> +    <domain includeSubdomains="true">192.168.2.3</domain>
Is this suppose to remain here?

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingPaymentProofSubmissionImpl.kt
> +    private var api: BdsApi? = null//TODO Rename BdsInAppApi
TODO. Forgot or for the future?

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/SubscriptionsResponse.kt
> +  REVOKED//The subscription purchase has been explicitly revoked and a refund was issued to the buyer.
kudis for the explanation comments

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsApiResponseMapper.kt
> +              it.price.fiat.currency.symbol), "inapp", null, null, null)
I don't think the last 2 parameters are not easy to understand what they are? can you add comments? plus maybe aggregate them in an object if they are all related to subs. Why are they being passed as null

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsApiResponseMapper.kt
> +  //TODO This method does nothing. Needs to me implemented
TODO. Forgot or for the future?

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
> +    }
Discuss. Don't you think it should be the remote repository to know which api to call?

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
> +    }
Same as above

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
> +    }
Same as above

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
> +    }
Same as above

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BillingSupportedType.kt
> +    fun valueOfInsensitive(value: String): BillingSupportedType {
Why insensitive?

2020-04-08 14:05 UTC, JDSM01 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
> +    return inapApi.consumePurchase(packageName, purchaseToken, walletAddress, walletSignature,
Change to inAppApi

2020-04-08 14:05 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingBinder.kt
> +        || billingType.isBlank()) {
Not yours, but extract it to a private method

2020-04-08 14:05 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingBinder.kt
> +      with(result) { putInt(RESPONSE_CODE, RESULT_DEVELOPER_ERROR) }
Why with? You gain nothing in this case. But I'll let it pass :P

2020-04-08 14:05 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingBinder.kt
> +    if (billingType == ITEM_TYPE_INAPP || billingType == ITEM_TYPE_SUBS) {
Extract to private method

2020-04-08 14:05 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingReceiverActivity.kt
> +      }
I think so, as it's being done in the pay as guest

2020-04-09 13:34 UTC, carvalho2707 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsApiResponseMapper.kt
> +  //TODO This method does nothing. Needs to me implemented
For the future. To prevent multiple conflicts

2020-04-09 13:35 UTC, carvalho2707 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
> +    }
I think we should have a InAppRemoteRepository and a SubsRemoteRepository.
But will delay the implementation to prevent conflicts

2020-04-09 13:36 UTC, carvalho2707 commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingPaymentProofSubmissionImpl.kt
> +    private var api: BdsApi? = null//TODO Rename BdsInAppApi
For the future. To prevent multiple conflicts

2020-04-09 13:43 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/util/EIPTransactionParser.java
> +    transactionBuilder.setType("inapp");//TODO pre subscriptions
It's because I don't know what kind of support we will have. and I left the TODO  for future reference

2020-04-14 08:50 UTC, JDSM01 requested changes

2020-04-14 08:50 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingBinder.kt
> +      with(result) { putInt(RESPONSE_CODE, RESULT_DEVELOPER_ERROR) }
Does this launches an exception? Why the differente behaviour here?

2020-04-14 08:50 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingBinder.kt
> +    requireNotNull(sku!!)
Is this required? if they are null the function will not reach here

2020-04-14 08:50 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingBinder.kt
> +      }
Again, why the try & catch?

2020-04-14 08:50 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingReceiverActivity.kt
> +          } catch (e: Exception) {
Again, why the try catch

2020-04-14 08:50 UTC, JDSM01 commented on billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingReceiverActivity.kt
> +      with(result) {
Same as before

2020-04-14 10:01 UTC, merged