[MOB-469] PoA Analytics
Aptoide/appcoins-wallet-android pull request #705
Opened 2020-04-13 13:55 UTC by paquiquinho

**What does this PR do?**

This PR added Rakam analytics for PoA;

**Database changed?**

No

**Where should the reviewer start?**

- [ ] PoaAnalytics.java

**How should this be manually tested?**

Make sure the events in the ticket are being sent;

**What are the relevant tickets?**

  Tickets related to this pull-request: [MOB-469](https://aptoide.atlassian.net/browse/MOB-469)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-04-13 16:58 UTC, JDSM01 requested changes

2020-04-13 16:58 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/advertise/WalletPoAService.java
> +                .equals(ProofStatus.COMPLETED)) {
Can't this just be an else?
Processing and submitting are not "isTerminate" so if the chain reaches here we know that it wasn't with those 2 cases. And this else is from if(COMPLETED) so no need for that also

2020-04-13 16:58 UTC, JDSM01 requested changes
Conflicts
Shouldn't we also add an error event on line 121 of the WalletPoaService.java?

2020-04-13 16:59 UTC, carvalho2707 requested changes

2020-04-13 16:59 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/advertise/WalletPoAService.java
>      if (completedEventDisposable == null || completedEventDisposable.isDisposed()) {
Can't we handle both scenarios in the same place?
Also, can we extract the logic to a private method so the main method continues readable?

2020-04-13 16:59 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/advertise/WalletPoAService.java
>      if (completedEventDisposable == null || completedEventDisposable.isDisposed()) {
this applies for the hole method

2020-04-14 14:28 UTC, JDSM01 approved these changes

2020-04-14 14:29 UTC, merged