[MOB-385] top up with local payments
Aptoide/appcoins-wallet-android pull request #848
Opened 2020-06-12 13:38 UTC by JDSM01

**What does this PR do?**

Adds local payments to top up
(The flow still isn't fully working as it still requires minor development from the API, we then need to check if both sync and async are differentiated correctly, everything else should be working fine).

**Database changed?**

   No

**Where should the reviewer start?**

TopUpFragmentPresenter.kt

**How should this be manually tested?**

Do a purchase with a sync and an async payment. 
Also try it with the most recent local payments

**What are the relevant tickets?**

https://aptoide.atlassian.net/browse/MOB-385

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-07-21 16:07 UTC, JoaoRaimundo requested changes

2020-07-21 16:07 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/billing/purchase/LocalPayementsLinkRepository.kt
> -            originalCurrency,
Can we fix the typo in the name of this class

2020-07-21 16:07 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
> +            view.setupCurrency(LocalCurrency(values.maxValue.symbol, values.maxValue.currency))
Please add event and log for erro, to be able to provide better support

2020-07-21 16:07 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
>      if (throwable.isNoNetworkException()) view.showNoNetworkError()
Please add other error handlers and send event/log for error to provide better support

2020-07-21 16:07 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
>                .doOnError { it.printStackTrace() }
If we have a a print stacktrace in the subscribe call why do we need one here?
Also should we add logging or error event?

2020-07-21 16:07 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpPresenter.kt
>            handleSpecificError(R.string.unknown_error)
Please add error logging and event in the handleSpecificError method

2020-07-21 16:07 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/LocalTopUpPaymentPresenter.kt
> +    when (status) {
When we have an error state should we send event/log reporting the error?

2020-07-21 16:07 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/LocalTopUpPaymentPresenter.kt
> +  private fun showError(throwable: Throwable) {
This and the showGenericError methods should include logic to send event and log error so we can improve the quality of our support

2020-07-21 16:07 UTC, JoaoRaimundo commented on app/src/main/res/layout-land/topup_pending_user_payment_view.xml
> +    xmlns:tools="http://schemas.android.com/tools"
The layout should be:
- Title and animation on top
- Text points in the middle
- Button on the bottom
All with the standard margins applied
The same logic should be applied in the landscape layout

2020-07-21 16:07 UTC, JoaoRaimundo commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
> +          it.printStackTrace()
Should we also log the error?

2020-07-23 13:07 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
>      if (throwable.isNoNetworkException()) view.showNoNetworkError()
This will be done in a different PR.

2020-07-23 13:08 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/payment/AdyenTopUpPresenter.kt
>            handleSpecificError(R.string.unknown_error)
This will be done in a different PR.

2020-07-23 13:08 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/LocalTopUpPaymentPresenter.kt
> +    when (status) {
This will be done in a different PR.

2020-07-23 13:08 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
> +            view.setupCurrency(LocalCurrency(values.maxValue.symbol, values.maxValue.currency))
This will be done in a different PR.

2020-07-23 13:09 UTC, JoaoRaimundo commented on app/src/main/java/com/asfoundation/wallet/topup/LocalTopUpPaymentPresenter.kt
> +  private fun showError(throwable: Throwable) {
This will be done in a different PR.

2020-07-23 13:09 UTC, JoaoRaimundo commented on bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
> +          it.printStackTrace()
This will be done in a different PR.

2020-08-07 14:41 UTC, carvalho2707 approved these changes

2020-08-07 14:41 UTC, merged