[MOB-760] Send error details to rakam
Aptoide/appcoins-wallet-android pull request #870
Opened 2020-07-09 16:26 UTC by JDSM01

**What does this PR do?**

Adds more details (error code and body) to the logs to rakam

**Database changed?**

No

**Where should the reviewer start?**

OnChainBuyPresenter**.kt**
AppcoinsRewardsBuyPresenter**.kt**

**How should this be manually tested?**

Do a purchase with both credits and APPC (one step and normal) and check if nothing breaks due to the moving from java to kotlin
Try to get a non-403 in both and check if it's logging the event to rakam

**What are the relevant tickets?**

https://aptoide.atlassian.net/browse/MOB-760

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-07-13 10:02 UTC, carvalho2707 requested changes

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/repository/WatchedTransactionService.kt
> +                      }
Code style here

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyView.kt
> -internal interface AppcoinsRewardsBuyView {
split lines with line breaks

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/Payment.java
>    private @Nullable final String orderReference;
In this class there are constructor parameters that should be annotated with @Nullable

2020-07-13 10:02 UTC, carvalho2707 commented on appcoinsRewards/src/main/java/com/appcoins/wallet/appcoins/rewards/AppcoinsRewards.kt
>    fun pay(amount: BigDecimal,
We should fix the code style in this method's arguments

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/RewardsManager.kt
> +  val balance: Single<BigDecimal>
since it's a variable move the declaration to the beginning of the file

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +            .observeOn(networkScheduler)
this observe is not needed here

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +        .throttleFirst(50, TimeUnit.MILLISECONDS)
add observe on view scheduler to make sure it doesn't run on computation 🥇

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +    disposables.add(onChainBuyInteract.parseTransaction(uriString, isBds)
shouldn't we try to run this in a network thread ?

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +class OnChainBuyPresenter(private val view: OnChainBuyView,
this is not something we need to change but why are we using a logger here and for every error we use that log and in the rest of the app we simply use it.printStackTrace?

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +            .observeOn(AndroidSchedulers.mainThread())
replace with variable viewscheduler

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +        onChainBuyInteract.getCompletedPurchase(transaction, isBds)
showPendingTransaction is called in the main thread. shouldn't we change to network?

2020-07-13 10:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +      bundle
Bundle().also {
        it.putInt(IabActivity.RESPONSE_CODE, 0)
        it.putString(IabActivity.TRANSACTION_HASH, payment.buyHash)
      }

2020-07-13 14:41 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +    disposables.add(onChainBuyInteract.parseTransaction(uriString, isBds)
Yes, but this chain has a lot of thread changing at repo level so it's better not to change

2020-07-13 14:45 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
> +        onChainBuyInteract.getCompletedPurchase(transaction, isBds)
Same as above

2020-07-15 11:42 UTC, carvalho2707 approved these changes

2020-07-15 12:22 UTC, merged