Feature/mob 865 perks promotions
Aptoide/appcoins-wallet-android pull request #903
Opened 2020-08-26 13:19 UTC by carvalho2707

**What does this PR do?**

This PR introduces a rework in the promotion section.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] PromotionsActivity

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [MOB-865](https://aptoide.atlassian.net/browse/MOB-865)

**What are the relevant tickets?**

  Tickets related to this pull-request: [MOB-865](https://aptoide.atlassian.net/browse/MOB-865)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-08-28 09:40 UTC, JDSM01 requested changes

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsFragment.kt
> +            AndroidSchedulers.mainThread())
Codestyle can be improved

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsGamificationAdapter.kt
> +class PromotionsGamificationViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
Extract to different file

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
> +    const val DEFAULT_VIEW_TYPE = "DEFAULT"
Not being used

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
> +          )
Codestyle can be improved by moving the ")"

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
> +                    hasGenericUpdate(generic, wallet.address, promotionUpdateScreen),
Aren't Generic Responses always perks?

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsViewHolder.kt
> +    }
Improve codestyle

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/referrals/ReferralInteractor.kt
> +      defaultWallet.find()
You can use the address from the class who calls this method

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationInteractor.kt
> +      defaultWallet.find()
Same as before, it can use the wallet from the previous class

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/LevelResourcesMapper.kt
> -          3 -> R.drawable.ic_level_star_dark
Did you check if these drawables could be deleted?

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/SharedPreferencesGamificationLocalData.kt
> +        false)
Codestyle can be improved

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/SharedPreferencesGamificationLocalData.kt
> +        }
Codestyle can be improved

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/SharedPreferencesGamificationLocalData.kt
> +              it.linkedPromotionId, it.objectiveProgress, it.startDate, it.title!!, it.viewType!!
Codestyle can be improved

2020-08-28 09:40 UTC, JDSM01 commented on app/src/main/res/layout/layout_promotions_update.xml
> +    app:cardElevation="2.01dp"
2.01?

2020-08-28 09:40 UTC, JDSM01 commented on gamification/src/main/java/com/appcoins/wallet/gamification/Gamification.kt
> +    } as ReferralResponse?
Codestyle can be improved here by adding a break line in the .firstOrNull

2020-08-28 09:40 UTC, JDSM01 commented on gamification/src/main/java/com/appcoins/wallet/gamification/Gamification.kt
> +    const val PROGRESS_VIEW_TYPE = "PROGRESS"
Not being used, should it not being used?

2020-08-28 09:40 UTC, JDSM01 commented on gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
> +      return if (isNoNetworkException(throwable)) {
2 Returns damn, it looks weird, but maybe it's just me XD

2020-08-28 09:40 UTC, JDSM01 commented on gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
> +            PromotionsResponse.Status.ACTIVE == gamification.status)
Codestyle can be improved

2020-08-28 09:40 UTC, JDSM01 commented on gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
> +          it.printStackTrace()
Codestyle can be improved

2020-08-28 09:40 UTC, JDSM01 commented on gamification/src/main/java/com/appcoins/wallet/gamification/repository/GamificationApi.kt
> +                   @Query("language") language: String = "en"): Single<UserStatusResponse>
Add //TODO to "language"

2020-08-28 09:40 UTC, JDSM01 commented on gamification/src/main/java/com/appcoins/wallet/gamification/repository/PromotionTypeConverter.kt
> +    }
Codestyle improvement

2020-08-28 09:40 UTC, JDSM01 commented on gamification/src/main/java/com/appcoins/wallet/gamification/repository/PromotionTypeConverter.kt
> +    }
Codestyle improvement

2020-08-28 09:48 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
> +                    hasGenericUpdate(generic, wallet.address, promotionUpdateScreen),
Yes, or it could be something that we don't know and it will fall in the generic case

2020-08-28 14:35 UTC, JDSM01 requested changes
- [x] Apps bundle isn't appearing on the transactions screen

- [ ] Remaining days may appear as -1

- [ ] Progress bar is bigger than in zeplin

- [ ] Gamification margin left is bigger than in zeplin

- [ ] The screen should rotate

- [ ] The top scroll feedback appears in the wrong place (just remove it)

- [ ] If I enter the promotion screen with no network it shows "Earn 0.0% bonus"

2020-08-31 11:29 UTC, JDSM01 requested changes

2020-08-31 11:29 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/SharedPreferencesGamificationLocalData.kt
> +  override fun insertLevels(levelsResponse: LevelsResponse): Completable {
Name is different from the one in the interface

2020-08-31 11:29 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/SharedPreferencesGamificationLocalData.kt
> +        BiFunction { t1, t2 -> mapToLevelsResponse(t1, t2) }
Name t1 and t2

2020-08-31 16:29 UTC, merged