MOB-1005 Gamification progress disclaimer
Aptoide/appcoins-wallet-android pull request #941
Opened 2020-10-06 08:56 UTC by JoaoRaimundo

**What does this PR do?**

Added bottom sheet disclaimer with details regarding the requirements to level up of the gamification, on the promotions screen and gamification screen

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] PromotionsActivity.kt
- [ ] PromotionsFragment.kt 
- [ ] PromotionsFragmentPresenter.kt 
- [ ] GamificationActivity.kt 
- [ ] GamificationFragment.kt 
- [ ] GamificationPresenter.kt 

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [MOB-1005](https://aptoide.atlassian.net/browse/MOB-1005)

**What are the relevant tickets?**

  Tickets related to this pull-request: [MOB-1005](https://aptoide.atlassian.net/browse/MOB-1005)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-10-06 11:02 UTC, carvalho2707 requested changes

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsActivity.kt
> +  }
Can be simplified to 

`override fun backPressed() = onBackPressedSubject!!`

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsFragment.kt
> +            }
Can be implemented in a single line:

`if (slideOffset == 0f) bottomsheet_coordinator_container.visibility = GONE`

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/promotions/PromotionsFragmentPresenter.kt
> +        }
Merge to a single line

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationActivity.kt
> +  }
Can be simplified to

override fun backPressed() = onBackPressedSubject!!

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationFragment.kt
>    override fun onAttach(context: Context) {
Add line break here

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationFragment.kt
> +            }
Lines can be merged as explained above

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationPresenter.kt
> +        }
Merge lines for a better code style

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/res/layout/gamification_info_bottom_sheet.xml
> +    android:background="@drawable/background_card"
1. This background has corners in the bottom side.
Consider using background_white_card_top.xml that was created for this purpose.

2. Both backgrounds only have 8dp radius instead of the 28 dp  specified in zeplin

2020-10-06 11:02 UTC, carvalho2707 commented on app/src/main/res/layout/gamification_info_bottom_sheet.xml
> +      style="@style/BottomSheetInfoTextStyle"
We are missing the android:lineSpacingExtra as in zeplin

2020-10-06 15:41 UTC, JoaoRaimundo commented on app/src/main/res/layout/gamification_info_bottom_sheet.xml
> +    android:background="@drawable/background_card"
After checking with the design team, the value should be the same as used currently in other cards, so I will be using the existing background_white_card_top.xml as background

2020-10-07 13:28 UTC, carvalho2707 approved these changes

2020-10-07 13:28 UTC, merged